const config = {
    SPEED: {
        max_speed: "25",
        normal_speed: "20",
        min_speed: "20",
        intersection_speed: "15",
        parking_speed: "10",
        gear_ratio: "1.7",
        speedrun: "OFF",
    },
    STEER: {
        max_abs_steer: "25",
        max_lk_steer: "25",
    },
    HARDWARE: {
        enablecamerastable: "ON",
        enablecamerarotating: "ON",
        enableimu: "ON",
        enablemove: "ON",
        enable_rotating_default: "OFF",
        enable_stable_default: "ON",
    },
    NAVIGATION: {
        enablelanekeeping: "ON",
        enableinternav: "ON",
        enableparking: "ON",
        enableovertake: "OFF",
        enablereactions: "ON",
        enableroundaboutnav: "OFF",
        ramp_pitch_thres: "-6",
        ramp_speed_factor: "1.0",
    },
    DETECTIONS: {
        enableobs: "ON",
        enablevehicle: "OFF",
        enablesign: "ON",
        enableped: "OFF",
        enablelane: "ON",
        enablehorizontal: "ON",
        camera_to_nose: "90",
        noise_excl_threshold: "5",
    },
    REACTIONS: {
        sign_distance: "700",
        obs_stop_distance: "600",
        obs_decel_distance: "800",
        odometry_margin: "100",
        sign_reset_interval: "3",
        obs_interval: "5",
        detections_thres: "1",
        stop_duration: "5",
        crosswalk_duration: "5",
        inter_completed_perc: "0.2",
    },
    PATH: {
        graph_name: "Lab_2024_1st_map_overtake",
        must_nodes: "ON",
        source: "7",
        target: "56",
        num_search: "6",
        wait_gps_repeats: "10",
        yaw_margin: "30",
        num_of_close_nodes: "6",
        coor_diff_thres: "0.5",
    },
    MUST_FLAGS: {
        parking: "ON",
        ramp: "ON",
        roundabout: "ON",
        highway: "ON",
        speedcurve: "ON",
        buslane: "ON",
        missingline: "ON",
        center_intersections: "ON",
    },
    DATA: {
        enablesemaphores: "ON",
        enabletrafficcommunication: "ON",
        server_public_key_loc: "src/data/trafficCommunication/src/publickey_server_test.pem",
        stream_threshold: "10",
    },
    STEPS: {
        step_dt: "0.1",
        lk_step_dt: "0.02",
        gui_step_dt: "0.2",
        overtake_step_dt: "0.02",
        latencies_threshold: "0.25",
    },
    GUI: {
        stream_data: "ON",
        config_from_gui: "ON",
        stream_img_compression_rate: "4",
        publish_frames: "ON",
        fps_rolling_window: "50",
        annotate_vehicles: "OFF",
        annotate_signs: "ON",
        annotate_ped: "OFF",
        annotate_lines: "OFF",
        annotate_horizontal: "OFF",
        annotate_obs: "ON",
    },
    CAM: {
        s: "455",
        r: "405",
        imgw: "848",
        imgh: "480",
        fps: "15",
        focal_length: "1.93",
        hfov_455: "90",
        vfov_455: "64",
        hfov_405: "84",
        vfov_405: "58",
        enable_spatial_filter: "OFF",
        enable_temporal_filter: "OFF",
        enable_threshold_filter: "ON",
        enable_holefilling_filter: "OFF",
        save_color_img: "OFF",
        save_depth_img: "OFF",
        save_lane_img: "OFF",
    },
    LOG: {
        cutelog_ip: "192.168.0.20",
        cutelog_port: "19996",
        logfile: "log_full.log",
    },
    LANE_DETECT: {
        lane_cam: "S",
        slice_step: "5",
        min_pulse_boom: "140",
        min_pulse_platue: "175",
        min_pixels_to_platue: "4",
        winning_percentage: "0.25",
        lower_pixel_limit: "15",
        upper_pixel_limit: "50",
        max_grouping_radius: "80",
        max_grouping_radius_horizontal: "40",
        min_boundary_gap: "0.3",
        min_gaps: "2",
        minimum_points_in_line: "10",
        minimum_points_in_horizontal_line: "15",
        top_row_divider: "2.0",
        resize_img: "0.4",
        confidence_interval: "0.08",
        horizontal_line_curvature: "1e-04",
        horizontal_line_tilt: "20",
        distance_from_front_car: "150.0",
    },
    CROSSWALK: {
        min_slice_count: "2.5",
    },
    LANE_KEEPING: {
        straight_course_gain_multiplier: "1.0",
        turn_gain_multiplier: "0.6",
        max_change_angle: "15.0",
        margin_from_side: "190.0",
    },
    OVERTAKE: {
        prev_cur_diff_1: "80",
        prev_cur_diff_2: "100",
        steer_factor: "0.6",
    },
    PARKING_DETECT: {
        parking_front_cam: "S",
        parking_back_cam: "R",
        canny_threshold_1: "80",
        canny_threshold_2: "150",
        hough_threshold: "50",
        hough_min_line_length: "50",
        hough_max_line_gap: "15",
        close_distance_theshold: "100",
        distance_threshold: "100",
        corner_age_threshold: "3",
        radius: "30.0",
        angle_limit: "20.0",
        horizontal_threshold: "10.0",
        lane_threshold: "5.0",
        obstacle_distance_threshold: "500",
        print_parking_detections: "OFF",
    },
    PARKING_MANEUVER: {
        destination_offset: "180",
        parking_speed: "15",
        odometry_threshold: "1000.0",
        correction_distance_from_horizontal: "450.0",
        drive_off_percentage: "0.3",
        dist_to_drive_off: "80.0",
        time_step: "0.01",
        dt: "0.1",
        quintic_s_vel: "0.05",
        quintic_g_vel: "0.05",
        quintic_s_accel: "0.01",
        quintic_g_accel: "0.01",
        quintic_max_jerk: "0.05",
        quintic_max_accel: "0.01",
        parking_wait_time: "5.0",
        show_animation: "OFF",
    },

    OBS_DETECT: {
        obs_cam: "S",
        enable_default: "ON",
        slice_step: "15",
        dbscan_min_samples: "3",
        dbscan_eps: "80",
        crop_top: "0.33",
        crop_left: "0.1",
        w_top: "0.45",
        w_base: "0.15",
        h_top: "0.2",
        h_base: "1.0",
        peak_threshold: "0.3",
        min_area_thres: "2000",
        max_rect_ratio: "2.5",
        visualize: "OFF",
        custom_distance: "OFF",
    },
    PED_DETECT: {
        ped_cam: "S",
        enable_default: "ON",
        network: "densenet121-body",
        conf_thres: "0.1",
        w_top: "0.1",
        h_top: "0.1",
        w_base: "0.1",
        h_base: "1.0",
    },
    SIGN_DETECT: {
        signs_cam: "S",
        enable_default: "ON",
        conf_thres: "0.3",
        bottom_perc: "0.2",
        img_size: "800",
        top_margin_width: "0",
        model_path: "src/utils/autonomous/signDetection/yolov7-tiny-updated-800-nms.trt",
    },
    VEHICLE_DETECT: {
        vehicle_cam: "S",
        enable_default: "OFF",
        w_top: "0.2",
        h_top: "0.1",
        w_base: "0.2",
        h_base: "1",
        mask_rect: "ON",
        keep_track: "ON",
        overlap_thres: "0.6",
        lower_bound: "110, 0, 0",
        upper_bound: "150, 50, 50",
        model_path: "/usr/local/bin/networks/FCN-ResNet18-Cityscapes-1024x512/",
        bounding_margin: "20",
        contour_area_threshold: "3000",
    },
    SPEED_ADAPT: {
        both_lines_w: "1.0",
        object_det_w: "1.0",
        abs_steer_w: "1.0",
        ped_dist_thres: "600",
        steer_thres_factor: "0.3",
    },
    IMAGE_TO_WORLD: {
        height_of_camera_455: "185",
        height_of_camera_405: "235",
        theta_455: "23",
        theta_405: "19",
        margin_ratio: "1.5",
    },
    INTERSECTION_NAV: {
        inter_dt: "0.1",
        num_points: "200",
        negative_ycoo: "True",
        inter_start: "1",
        inter_end: "2",
        v_step: "2",
        path_complete: "0.7",
        k: "2",
        map_yaw_diff: "0",
        min_horizontal_time_found: "1",
        min_horizontal_time_lost: "2",
        max_dydx: "8",
        min_node_distance: "1",
        max_horizontal_distance: "200",
        steer_thr: "3",
        lk_steer_trust: "0.8",
        yaw_threshold: "20",
        dfactor_straight: "1.5",
        dfactor_left: "0.5",
        dfactor_right: "2.0",
    },
};

export default config;
